{
 "title": "Flask Web App",
 "description": "Dashboard for official Prometheus Python Client's metrics",
 "tags": [
  "flask",
  "app",
  "web",
  "python"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "job name",
    "query": "label_values(app_version_info, job)"
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "label_values(app_request_latency_seconds_bucket, endpoint)"
   },
   {
    "name": "method",
    "label": "HTTP Method",
    "query": "label_values(app_request_latency_seconds_bucket, method)"
   },
   { "name": "percentile", "label": "Percentile", "query": "100,99,95,90,75,50,25" },
   {
    "name": "error_code",
    "label": "Status code 4xx or 5xx",
    "query": "label_values(app_request_count_total, http_status)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "description": "Requests per second ",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_request_count_total{job=~\"$job\", endpoint=~\"$endpoint\",method=~\"$method\"}[$interval])",
     "legendFormat": "{{ job }} - {{ endpoint }}"
    }
   ]
  },
  {
   "title": "Request Latency, s",
   "type": "graph",
   "description": "Latency per job, endpoint and method",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(app_request_latency_seconds_sum{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\"}[$interval]) \n/ \nrate(app_request_latency_seconds_count{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\"}[$interval])",
     "legendFormat": "{{ method }} {{ job }}{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Latency within which $percentile% of requests served",
   "type": "graph",
   "description": "See more:\nhttps://prometheus.io/docs/practices/histograms/",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum(rate(app_request_latency_seconds_bucket[$interval])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{http_status=~\"4..|5..\", job=~\"$job\"}[$interval]))",
     "legendFormat": " Errors per second"
    },
    {}
   ]
  },
  {
   "title": "4xx, 5xx errors count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "app_request_count_total{http_status=~\"$error_code\", job=~\"$job\", method=~\"$method\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{ http_status }} {{ job }} {{ endpoint }}"
    },
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(process_open_fds{job=~\"$job\"})",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "job's Uptime - $job",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 },
   "repeat": "job",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "job's App Version -  $job",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 61 },
   "repeat": "job",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "app_version_info{job=~\"$job\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "job's App Config  - $job",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 88 },
   "repeat": "job",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "app_version_info{job=~\"$job\"}",
     "legendFormat": "{{ config }}"
    }
   ]
  },
  {
   "title": "job's Python Version  - $job",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 115 },
   "repeat": "job",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "python_info{job=~\"$job*\"}",
     "legendFormat": "{{ implementation }} {{ version }}"
    }
   ]
  }
 ]
}